import { RolPrecio } from '@prisma/client';
import { CreateNewProductDto } from '../dto/create-productNew.dto';
const ROL_PUBLICO = RolPrecio.PUBLICO;

export const itemsBase /* : CreateNewProductDto[] */ = [
  {
    codigoProducto: 'GT-AGR-0001',
    codigoProveedor: 'PROV-AG-0001',
    nombre: 'Semilla de maíz híbrido 10 kg',
    descripcion: 'Semilla certificada para alto rendimiento.',
    precioCostoActual: 280.0,
    precioVenta: [{ precio: '380.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-AGR-0002',
    codigoProveedor: 'PROV-AG-0002',
    nombre: 'Semilla de frijol negro 5 kg',
    descripcion: 'Variedad adaptada a climas locales.',
    precioCostoActual: 160.0,
    precioVenta: [{ precio: '220.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-AGR-0003',
    codigoProveedor: 'PROV-AG-0003',
    nombre: 'Urea 46-0-0 50 kg',
    descripcion: 'Fertilizante nitrogenado de rápida acción.',
    precioCostoActual: 280.0,
    precioVenta: [{ precio: '360.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-AGR-0004',
    codigoProveedor: 'PROV-AG-0004',
    nombre: 'NPK 15-15-15 50 kg',
    descripcion: 'Fertilizante balanceado para diversos cultivos.',
    precioCostoActual: 300.0,
    precioVenta: [{ precio: '390.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-AGR-0005',
    codigoProveedor: 'PROV-AG-0005',
    nombre: 'Cal agrícola 25 kg',
    descripcion: 'Mejora pH del suelo y disponibilidad de nutrientes.',
    precioCostoActual: 80.0,
    precioVenta: [{ precio: '115.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-AGR-0006',
    codigoProveedor: 'PROV-AG-0006',
    nombre: 'Sulfato de amonio 50 kg',
    descripcion: 'Fuente de nitrógeno y azufre para el suelo.',
    precioCostoActual: 260.0,
    precioVenta: [{ precio: '340.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-AGR-0007',
    codigoProveedor: 'PROV-AG-0007',
    nombre: 'Herbicida glifosato 1 L',
    descripcion: 'Control de malezas no selectivo.',
    precioCostoActual: 120.0,
    precioVenta: [{ precio: '165.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-AGR-0008',
    codigoProveedor: 'PROV-AG-0008',
    nombre: 'Herbicida 2,4-D 1 L',
    descripcion: 'Control de malezas de hoja ancha.',
    precioCostoActual: 95.0,
    precioVenta: [{ precio: '130.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-AGR-0009',
    codigoProveedor: 'PROV-AG-0009',
    nombre: 'Insecticida lambda-cyhalothrin 250 ml',
    descripcion: 'Control de insectos masticadores y chupadores.',
    precioCostoActual: 85.0,
    precioVenta: [{ precio: '120.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-AGR-0010',
    codigoProveedor: 'PROV-AG-0010',
    nombre: 'Insecticida cipermetrina 1 L',
    descripcion: 'Amplio espectro, uso agrícola.',
    precioCostoActual: 140.0,
    precioVenta: [{ precio: '190.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-AGR-0011',
    codigoProveedor: 'PROV-AG-0011',
    nombre: 'Fungicida mancozeb 1 kg',
    descripcion: 'Protección preventiva contra hongos foliares.',
    precioCostoActual: 110.0,
    precioVenta: [{ precio: '155.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-AGR-0012',
    codigoProveedor: 'PROV-AG-0012',
    nombre: 'Fungicida a base de cobre 1 kg',
    descripcion: 'Bactericida y fungicida de contacto.',
    precioCostoActual: 95.0,
    precioVenta: [{ precio: '135.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-AGR-0013',
    codigoProveedor: 'PROV-AG-0013',
    nombre: 'Bomba de mochila 16 L',
    descripcion: 'Aspersora manual para aplicaciones en campo.',
    precioCostoActual: 340.0,
    precioVenta: [{ precio: '460.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 4,
  },
  {
    codigoProducto: 'GT-AGR-0014',
    codigoProveedor: 'PROV-AG-0014',
    nombre: 'Manguera de riego 1/2" 50 m',
    descripcion: 'Manguera flexible para riego por gravedad.',
    precioCostoActual: 220.0,
    precioVenta: [{ precio: '299.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 5,
  },
  {
    codigoProducto: 'GT-AGR-0015',
    codigoProveedor: 'PROV-AG-0015',
    nombre: 'Regadera metálica 10 L',
    descripcion: 'Riego manual para viveros y huertos.',
    precioCostoActual: 120.0,
    precioVenta: [{ precio: '168.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 5,
  },
  {
    codigoProducto: 'GT-AGR-0016',
    codigoProveedor: 'PROV-AG-0016',
    nombre: 'Guantes de nitrilo agrícola (par)',
    descripcion: 'Protección química y mecánica.',
    precioCostoActual: 18.0,
    precioVenta: [{ precio: '28.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 20,
  },
  {
    codigoProducto: 'GT-AGR-0017',
    codigoProveedor: 'PROV-AG-0017',
    nombre: 'Botas de hule talla 42',
    descripcion: 'Calzado resistente para trabajo agrícola.',
    precioCostoActual: 120.0,
    precioVenta: [{ precio: '170.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-AGR-0018',
    codigoProveedor: 'PROV-AG-0018',
    nombre: 'Sombrero de palma',
    descripcion: 'Protección solar para jornada de campo.',
    precioCostoActual: 50.0,
    precioVenta: [{ precio: '75.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-AGR-0019',
    codigoProveedor: 'PROV-AG-0019',
    nombre: 'Carretilla 90 L',
    descripcion: 'Transporte de materiales y cosecha.',
    precioCostoActual: 520.0,
    precioVenta: [{ precio: '690.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 3,
  },
  {
    codigoProducto: 'GT-AGR-0020',
    codigoProveedor: 'PROV-AG-0020',
    nombre: 'Machete 22" con funda',
    descripcion: 'Herramienta de corte para labores agrícolas.',
    precioCostoActual: 90.0,
    precioVenta: [{ precio: '125.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-AGR-0021',
    codigoProveedor: 'PROV-AG-0021',
    nombre: 'Cuerda agrícola PP 200 m',
    descripcion: 'Amarre de tutores y usos generales.',
    precioCostoActual: 140.0,
    precioVenta: [{ precio: '195.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-AGR-0022',
    codigoProveedor: 'PROV-AG-0022',
    nombre: 'Plástico para invernadero 200 micras 4x10 m',
    descripcion: 'Cobertura resistente a rayos UV.',
    precioCostoActual: 650.0,
    precioVenta: [{ precio: '840.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 2,
  },
  {
    codigoProducto: 'GT-AGR-0023',
    codigoProveedor: 'PROV-AG-0023',
    nombre: 'Bandeja de germinación 128 cavidades',
    descripcion: 'Producción de plántulas uniforme.',
    precioCostoActual: 35.0,
    precioVenta: [{ precio: '55.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 20,
  },
  {
    codigoProducto: 'GT-AGR-0024',
    codigoProveedor: 'PROV-AG-0024',
    nombre: 'Sustrato para semillero 40 L',
    descripcion: 'Mezcla ligera y aireada para germinación.',
    precioCostoActual: 85.0,
    precioVenta: [{ precio: '120.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-AGR-0025',
    codigoProveedor: 'PROV-AG-0025',
    nombre: 'Sales minerales bovinos 25 kg',
    descripcion: 'Suplemento para ganado en pastoreo.',
    precioCostoActual: 210.0,
    precioVenta: [{ precio: '280.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-AGR-0026',
    codigoProveedor: 'PROV-AG-0026',
    nombre: 'Concentrado de engorde 40 kg',
    descripcion: 'Alimento balanceado para bovinos.',
    precioCostoActual: 320.0,
    precioVenta: [{ precio: '420.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-AGR-0027',
    codigoProveedor: 'PROV-AG-0027',
    nombre: 'Multivitamínico inyectable 100 ml',
    descripcion: 'Soporte nutricional para ganado.',
    precioCostoActual: 85.0,
    precioVenta: [{ precio: '125.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-AGR-0028',
    codigoProveedor: 'PROV-AG-0028',
    nombre: 'Melaza 3.5 L',
    descripcion: 'Energético para suplementación animal.',
    precioCostoActual: 45.0,
    precioVenta: [{ precio: '65.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-AGR-0029',
    codigoProveedor: 'PROV-AG-0029',
    nombre: 'Bebedero plástico 20 L',
    descripcion: 'Resistente y fácil de limpiar.',
    precioCostoActual: 120.0,
    precioVenta: [{ precio: '165.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 5,
  },
  {
    codigoProducto: 'GT-AGR-0030',
    codigoProveedor: 'PROV-AG-0030',
    nombre: 'Alambre galvanizado calibre 12.5 (rollo 400 m)',
    descripcion: 'Cercado perimetral para potreros.',
    precioCostoActual: 780.0,
    precioVenta: [{ precio: '980.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 3,
  },
];

const report: Array<{
  codigoProducto: string;
  status: 'created' | 'skipped' | 'error';
  error?: string;
}> = [];
