import { RolPrecio } from '@prisma/client';
import { CreateNewProductDto } from '../dto/create-productNew.dto';
const ROL_PUBLICO = RolPrecio.PUBLICO;

export const itemsBase = [
  {
    codigoProducto: 'GT-MED-0001',
    nombre: 'Acetaminofén 500 mg (10 tabs)',
    descripcion: 'Analgésico/antipirético de uso común.',
    precioCostoActual: 4.5,
    precioVenta: [{ precio: '6.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-MED-0002',
    nombre: 'Ibuprofeno 400 mg (10 tabs)',
    descripcion: 'Antiinflamatorio no esteroideo.',
    precioCostoActual: 6.5,
    precioVenta: [{ precio: '9.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-MED-0003',
    nombre: 'Loperamida 2 mg (6 caps)',
    descripcion: 'Antidiarreico de venta libre.',
    precioCostoActual: 8.5,
    precioVenta: [{ precio: '12.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-MED-0004',
    nombre: 'Sales de Rehidratación Oral (SRO) 1 sobre',
    descripcion: 'Reposición de líquidos y electrolitos.',
    precioCostoActual: 3.2,
    precioVenta: [{ precio: '4.50', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 20,
  },
  {
    codigoProducto: 'GT-MED-0005',
    nombre: 'Omeprazol 20 mg (14 caps)',
    descripcion: 'IBP para acidez y reflujo.',
    precioCostoActual: 13.5,
    precioVenta: [{ precio: '18.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-MED-0006',
    nombre: 'Loratadina 10 mg (10 tabs)',
    descripcion: 'Antihistamínico para alergias.',
    precioCostoActual: 9.5,
    precioVenta: [{ precio: '14.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-MED-0007',
    nombre: 'Jarabe para la tos (Dextrometorfano) 120 ml',
    descripcion: 'Antitusivo de uso común.',
    precioCostoActual: 16.0,
    precioVenta: [{ precio: '22.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 5,
  },
  {
    codigoProducto: 'GT-MED-0008',
    nombre: 'Alcohol en gel 70% 250 ml',
    descripcion: 'Higiene de manos.',
    precioCostoActual: 10.5,
    precioVenta: [{ precio: '15.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-MED-0009',
    nombre: 'Algodón 50 g',
    descripcion: 'Cuidado y curaciones.',
    precioCostoActual: 5.2,
    precioVenta: [{ precio: '8.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-MED-0010',
    nombre: 'Gasas estériles 10x10 cm (10 und)',
    descripcion: 'Curaciones y primeros auxilios.',
    precioCostoActual: 11.5,
    precioVenta: [{ precio: '16.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-MED-0011',
    nombre: 'Suero fisiológico 0.9% 500 ml',
    descripcion: 'Lavados y curaciones.',
    precioCostoActual: 7.0,
    precioVenta: [{ precio: '10.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
  {
    codigoProducto: 'GT-MED-0012',
    nombre: 'Diclofenaco gel 1% 60 g',
    descripcion: 'Antiinflamatorio tópico.',
    precioCostoActual: 20.0,
    precioVenta: [{ precio: '28.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-MED-0013',
    nombre: 'Povidona yodada 10% 120 ml',
    descripcion: 'Antiséptico para piel.',
    precioCostoActual: 13.5,
    precioVenta: [{ precio: '20.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 6,
  },
  {
    codigoProducto: 'GT-MED-0014',
    nombre: 'Vitamina C 500 mg (30 tabs)',
    descripcion: 'Suplemento vitamínico.',
    precioCostoActual: 18.0,
    precioVenta: [{ precio: '25.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-MED-0015',
    nombre: 'Pastillas para garganta (mentol-eucalipto) x24',
    descripcion: 'Alivio de irritación de garganta.',
    precioCostoActual: 12.5,
    precioVenta: [{ precio: '18.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-MED-0016',
    nombre: 'Antiácido masticable (Al+Mg) x24',
    descripcion: 'Alivio de acidez estomacal.',
    precioCostoActual: 12.0,
    precioVenta: [{ precio: '17.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 8,
  },
  {
    codigoProducto: 'GT-MED-0017',
    nombre: 'Termómetro digital',
    descripcion: 'Medición de temperatura corporal.',
    precioCostoActual: 24.0,
    precioVenta: [{ precio: '35.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 4,
  },
  {
    codigoProducto: 'GT-MED-0018',
    nombre: 'Pasta dental 100 ml',
    descripcion: 'Higiene bucal diaria.',
    precioCostoActual: 8.5,
    precioVenta: [{ precio: '12.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 12,
  },
  {
    codigoProducto: 'GT-MED-0019',
    nombre: 'Jabón antibacterial 90 g',
    descripcion: 'Aseo personal.',
    precioCostoActual: 4.0,
    precioVenta: [{ precio: '6.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 18,
  },
  {
    codigoProducto: 'GT-MED-0020',
    nombre: 'Toallas sanitarias (10 und)',
    descripcion: 'Cuidado femenino.',
    precioCostoActual: 16.0,
    precioVenta: [{ precio: '22.00', orden: 1, rol: ROL_PUBLICO }],
    categorias: [],
    presentaciones: [],
    stockMinimo: 10,
  },
];

const report: Array<{
  codigoProducto: string;
  status: 'created' | 'skipped' | 'error';
  error?: string;
}> = [];
